# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.12.0.schema.json

PackageIdentifier: ez3689.Breakout
PackageVersion: 1.0.0
PackageLocale: en-US
Publisher: ez3689
PackageName: Breakout
License: MIT License
ShortDescription: Breakout Setup
ManifestType: defaultLocale
ManifestVersion: 1.12.0
