# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: ez3689.Breakout
PackageVersion: 1.0.0
InstallerType: inno
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/ez3689/breakout/releases/download/1.0.0/Breakout-Setup.exe
  InstallerSha256: 3A268E61CF7B824FC12287F187D7E417F5CC87C001398071AEDCE2331E9DA08A
ManifestType: installer
ManifestVersion: 1.12.0
